(define (square x)
  (* x x))
(define (smallest-divisor n)
  (divisor n 2))
(define (divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides? n test-divisor) test-divisor)
        (else (divisor n (+ test-divisor 1)))))
(define (divides? a b)
  (=(remainder a b) 0))
(smallest-divisor 19999)

(define (prime? n)
  (= (smallest-divisor n) n))
(prime? 2)